const state={user:null,view:null,clientes:[],pedidos:[],ventas:[],inventario:[],token:null};
const accountsFallback=[{username:"admin",password:"agua2026",rol:"admin",nombre:"Admin"},{username:"reparto",password:"ruta2026",rol:"repartidor",nombre:"Reparto"}];
const nav=[{id:"dashboard",label:"Inicio",roles:["admin"]},{id:"ventas",label:"Ventas",roles:["admin"]},{id:"pedidos",label:"Pedidos",roles:["admin","repartidor"]},{id:"rutas",label:"Rutas",roles:["admin","repartidor"]},{id:"clientes",label:"Clientes",roles:["admin"]},{id:"inventario",label:"Inventario",roles:["admin"]},{id:"reportes",label:"Reportes",roles:["admin"]}];
let map;let mapLayer;let markers=[];
const auth=document.getElementById("auth");const layout=document.getElementById("layout");const menu=document.getElementById("menu");const view=document.getElementById("view");const userRole=document.getElementById("user-role");const today=document.getElementById("today");const toast=document.getElementById("toast");
function formatCurrency(value){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(value)}
function formatDate(value){return new Date(value).toLocaleDateString("es-MX",{day:"2-digit",month:"short",year:"numeric"})}
function formatTime(value){return new Date(value).toLocaleTimeString("es-MX",{hour:"2-digit",minute:"2-digit"})}
function priorityScore(cliente){return cliente.frecuencia*0.6+cliente.volumen*0.4}
function topClientes(){return [...state.clientes].sort((a,b)=>priorityScore(b)-priorityScore(a)).slice(0,3)}
function showToast(message,type="info"){toast.textContent=message;toast.classList.remove("hidden");toast.classList.add("show");toast.style.background=type==="error"?"#b91c1c":"#245b7f";setTimeout(()=>toast.classList.remove("show"),2600)}
function getAuthHeader(){return state.token?{Authorization:`Bearer ${state.token}`}:{}}
async function loadData(){
	try{
		const headers=getAuthHeader();
		const [clientesRes,pedidosRes,ventasRes,invRes] = await Promise.all([
			fetch('/api/clientes?zona=gabriel',{headers}),
			fetch('/api/pedidos?zona=gabriel',{headers}),
			fetch('/api/ventas',{headers}),
			fetch('/api/inventario',{headers})
		]);
		if(clientesRes.ok) state.clientes = await clientesRes.json();
		if(pedidosRes.ok) state.pedidos = await pedidosRes.json();
		if(ventasRes.ok) state.ventas = await vendasOrEmpty(ventasRes);
		if(invRes.ok) state.inventario = await invRes.json();
		renderView();
	}catch(e){
		showToast('No se pudo cargar datos','error');
	}
}

async function vendasOrEmpty(res){ try{return await res.json()}catch(e){return []} }
function setView(id){state.view=id;renderNav();renderView()}
function renderNav(){menu.innerHTML="";const filtered=nav.filter(item=>item.roles.includes(state.user.rol));filtered.forEach(item=>{const btn=document.createElement("button");btn.textContent=item.label;btn.className=item.id===state.view?"active":"";btn.onclick=()=>setView(item.id);menu.appendChild(btn)});if(!filtered.find(x=>x.id===state.view)){state.view=filtered[0].id}}
function renderView(){view.innerHTML="";if(state.view==="dashboard")renderDashboard();if(state.view==="ventas")renderVentas();if(state.view==="pedidos")renderPedidos();if(state.view==="rutas")renderRutas();if(state.view==="clientes")renderClientes();if(state.view==="inventario")renderInventario();if(state.view==="reportes")renderReportes()}
function renderDashboard(){const stats=document.createElement("div");stats.className="stats";const totalHoy=state.ventas.filter(v=>new Date(v.creado).toDateString()===new Date().toDateString()).reduce((a,b)=>a+b.total,0);const pedidosPend=state.pedidos.filter(p=>p.estado==="pendiente").length;const pedidosRuta=state.pedidos.filter(p=>p.estado==="en_ruta").length;const preferentes=topClientes().map(c=>c.nombre).join(", ");const statData=[{label:"Ingresos hoy",value:formatCurrency(totalHoy)},{label:"Pendientes",value:pedidosPend},{label:"En ruta",value:pedidosRuta},{label:"Prioridad",value:preferentes||"--"}];statData.forEach(s=>{const el=document.createElement("div");el.className="stat";const v=document.createElement("div");v.className="value";v.textContent=s.value;const l=document.createElement("div");l.textContent=s.label;el.appendChild(v);el.appendChild(l);stats.appendChild(el)});const priority=document.createElement("div");priority.className="tile";const ph=document.createElement("h3");ph.textContent="Clientes prioridad";priority.appendChild(ph);const list=document.createElement("div");list.className="list";topClientes().forEach(c=>{const item=document.createElement("div");item.className="list-item";const meta=document.createElement("div");meta.className="meta";meta.innerHTML=`<strong>${c.nombre}</strong><span>${c.direccion}</span>`;const pill=document.createElement("div");pill.className="pill";pill.textContent="Frecuente";item.appendChild(meta);item.appendChild(pill);list.appendChild(item)});priority.appendChild(list);view.appendChild(stats);view.appendChild(priority)}
function renderVentas(){const wrapper=document.createElement("div");wrapper.className="tile";const title=document.createElement("div");title.className="section-title";title.innerHTML="<h3>Ventas recientes</h3>";wrapper.appendChild(title);const table=document.createElement("table");table.className="table";table.innerHTML=`<thead><tr><th>ID</th><th>Cliente</th><th>Total</th><th>Método</th><th>Fecha</th></tr></thead>`;const body=document.createElement("tbody");state.ventas.slice(-10).reverse().forEach(v=>{const tr=document.createElement("tr");const cliente=state.clientes.find(c=>c.id===v.cliente_id);tr.innerHTML=`<td>${v.id}</td><td>${cliente?cliente.nombre:"Mostrador"}</td><td>${formatCurrency(v.total)}</td><td>${v.metodo}</td><td>${formatDate(v.creado)} ${formatTime(v.creado)}</td>`;body.appendChild(tr)});table.appendChild(body);wrapper.appendChild(table);view.appendChild(wrapper)}
function renderPedidos(){const wrapper=document.createElement("div");wrapper.className="tile";const header=document.createElement("div");header.className="section-title";header.innerHTML="<h3>Pedidos</h3>";wrapper.appendChild(header);const table=document.createElement("table");table.className="table";table.innerHTML=`<thead><tr><th>ID</th><th>Cliente</th><th>Cant.</th><th>Total</th><th>Estado</th><th>Hora</th><th></th></tr></thead>`;const body=document.createElement("tbody");const sorted=[...state.pedidos].sort((a,b)=>{const ca=priorityScore(state.clientes.find(c=>c.id===a.cliente_id)||{frecuencia:0,volumen:0});const cb=priorityScore(state.clientes.find(c=>c.id===b.cliente_id)||{frecuencia:0,volumen:0});return cb-ca});sorted.forEach(p=>{const tr=document.createElement("tr");const cliente=state.clientes.find(c=>c.id===p.cliente_id);const badge=p.estado==="pendiente"?"gray":p.estado==="en_ruta"?"blue":"green";tr.innerHTML=`<td>${p.id}</td><td>${cliente?cliente.nombre:""}</td><td>${p.cantidad}</td><td>${formatCurrency(p.total)}</td><td><span class="badge ${badge}">${p.estado.replace("_"," ")}</span></td><td>${formatTime(p.creado)}</td><td></td>`;const action=document.createElement("div");if(p.estado==="pendiente"){const btn=document.createElement("button");btn.textContent="Enviar";btn.onclick=()=>cambiarEstado(p.id,"en_ruta");action.appendChild(btn)}else if(p.estado==="en_ruta"){const btn=document.createElement("button");btn.textContent="Entregado";btn.onclick=()=>cambiarEstado(p.id,"entregado");action.appendChild(btn)}tr.lastChild.appendChild(action);body.appendChild(tr)});table.appendChild(body);wrapper.appendChild(table);view.appendChild(wrapper)}
function cambiarEstado(id,estado){const pedido=state.pedidos.find(p=>p.id===id);if(!pedido)return;pedido.estado=estado;const headers=getAuthHeader();fetch(`/api/pedidos/${id}/state`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({estado})}).then(r=>r.json()).catch(e=>console.error(e));renderView();showToast(`Pedido ${id} → ${estado}`)}
function renderRutas(){const wrapper=document.createElement("div");wrapper.className="tile";const header=document.createElement("div");header.className="section-title";header.innerHTML="<h3>Rutas</h3>";const action=document.createElement("div");action.className="input-inline";const btn=document.createElement("button");btn.textContent="Recalcular";btn.onclick=generarRuta;action.appendChild(btn);header.appendChild(action);wrapper.appendChild(header);const mapDiv=document.createElement("div");mapDiv.id="map";wrapper.appendChild(mapDiv);const lista=document.createElement("div");lista.className="list";wrapper.appendChild(lista);view.appendChild(wrapper);setTimeout(()=>{if(!map){map=L.map("map").setView([25.5653,-108.4473],13);mapLayer=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19});mapLayer.addTo(map)}renderMarkers(lista)},80)}
function renderMarkers(lista){markers.forEach(m=>map.removeLayer(m));markers=[];if(map&&map.eachLayer){map.eachLayer(layer=>{if(layer!==mapLayer)map.removeLayer(layer)})}const ruta=generarRuta(false);lista.innerHTML="";ruta.forEach((p,idx)=>{const cliente=state.clientes.find(c=>c.id===p.cliente_id);const marker=L.marker([cliente.lat,cliente.lng]).addTo(map);marker.bindPopup(`${idx+1}. ${cliente.nombre}`);markers.push(marker);const item=document.createElement("div");item.className="list-item";const meta=document.createElement("div");meta.className="meta";meta.innerHTML=`<strong>${idx+1}. ${cliente.nombre}</strong><span>${cliente.direccion}</span>`;const badge=document.createElement("div");badge.className="badge blue";badge.textContent=p.estado.replace("_"," ");item.appendChild(meta);item.appendChild(badge);lista.appendChild(item)});if(ruta.length>1){const latlngs=ruta.map(p=>{const c=state.clientes.find(x=>x.id===p.cliente_id);return [c.lat,c.lng]});L.polyline(latlngs,{color:"#245b7f"}).addTo(map);map.fitBounds(latlngs,{padding:[30,30]})}else if(ruta.length===1){const c=state.clientes.find(x=>x.id===ruta[0].cliente_id);map.setView([c.lat,c.lng],13)}}
function generarRuta(emit=true){const base={lat:25.5653,lng:-108.4473};const pendientes=state.pedidos.filter(p=>p.estado!=="entregado");const ruta=[];let current=base;const restantes=[...pendientes];while(restantes.length){restantes.sort((a,b)=>{const ca=dist(current,clientePos(a));const cb=dist(current,clientePos(b));return ca-cb});const next=restantes.shift();ruta.push(next);current=clientePos(next)}if(emit)showToast("Ruta actualizada");return ruta}
function clientePos(p){const c=state.clientes.find(x=>x.id===p.cliente_id);return {lat:c.lat,lng:c.lng}}
function dist(a,b){const dx=a.lat-b.lat;const dy=a.lng-b.lng;return Math.sqrt(dx*dx+dy*dy)}
function renderClientes(){const wrapper=document.createElement("div");wrapper.className="tile";const title=document.createElement("div");title.className="section-title";title.innerHTML="<h3>Clientes</h3>";wrapper.appendChild(title);const table=document.createElement("table");table.className="table";table.innerHTML=`<thead><tr><th>Nombre</th><th>Frecuencia</th><th>Volumen</th><th>Prioridad</th><th>Contacto</th></tr></thead>`;const body=document.createElement("tbody");state.clientes.forEach(c=>{const tr=document.createElement("tr");const pr=priorityScore(c);const badge=pr>40?"green":pr>30?"blue":"gray";tr.innerHTML=`<td>${c.nombre}</td><td>${c.frecuencia} pedidos</td><td>${c.volumen} garrafones</td><td><span class="badge ${badge}">P${Math.round(pr)}</span></td><td>${c.telefono}</td>`;body.appendChild(tr)});table.appendChild(body);wrapper.appendChild(table);view.appendChild(wrapper)}
function renderInventario(){const wrapper=document.createElement("div");wrapper.className="tile";const title=document.createElement("div");title.className="section-title";title.innerHTML="<h3>Inventario</h3>";wrapper.appendChild(title);const table=document.createElement("table");table.className="table";table.innerHTML=`<thead><tr><th>Item</th><th>Stock</th><th>Umbral</th><th>Estado</th></tr></thead>`;const body=document.createElement("tbody");state.inventario.forEach(i=>{const low=i.stock<=i.umbral;const badge=low?"amber":"green";const text=low?"Reponer":"OK";const tr=document.createElement("tr");tr.innerHTML=`<td>${i.item}</td><td>${i.stock}</td><td>${i.umbral}</td><td><span class="badge ${badge}">${text}</span></td>`;body.appendChild(tr)});table.appendChild(body);wrapper.appendChild(table);view.appendChild(wrapper)}
function renderReportes(){const wrapper=document.createElement("div");wrapper.className="grid";const tile1=document.createElement("div");tile1.className="tile";tile1.innerHTML=`<h3>Top clientes por volumen</h3>`;const list1=document.createElement("div");list1.className="list";[...state.clientes].sort((a,b)=>b.volumen-a.volumen).slice(0,3).forEach(c=>{const item=document.createElement("div");item.className="list-item";item.innerHTML=`<div class="meta"><strong>${c.nombre}</strong><span>${c.volumen} garrafones</span></div><div class="pill">Seguro</div>`;list1.appendChild(item)});tile1.appendChild(list1);const tile2=document.createElement("div");tile2.className="tile";tile2.innerHTML=`<h3>Top clientes por frecuencia</h3>`;const list2=document.createElement("div");list2.className="list";[...state.clientes].sort((a,b)=>b.frecuencia-a.frecuencia).slice(0,3).forEach(c=>{const item=document.createElement("div");item.className="list-item";item.innerHTML=`<div class="meta"><strong>${c.nombre}</strong><span>${c.frecuencia} pedidos</span></div><div class="pill">Constante</div>`;list2.appendChild(item)});tile2.appendChild(list2);wrapper.appendChild(tile1);wrapper.appendChild(tile2);view.appendChild(wrapper)}
function init(){today.textContent=new Date().toLocaleDateString("es-MX",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});document.getElementById("entrar").onclick=login;document.getElementById("logout").onclick=logout}
async function login(){
	const usuario=document.getElementById("usuario").value.trim();
	const password=document.getElementById("password").value;
	const rol=document.getElementById("rol").value;
	const errorBox=document.getElementById("auth-error");
	if(!usuario||!password){errorBox.textContent="Completa usuario y contraseña";return}
	try{
		const res = await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:usuario,password,rol})});
		if(!res.ok){
			// fallback local accounts for offline
			const match = accountsFallback.find(a=>a.username===usuario&&a.password===password&&a.rol===rol);
			if(!match){errorBox.textContent='Datos no válidos';showToast('Acceso denegado','error');return}
			state.user = match;
		}else{
			const data = await res.json();
			state.user = data.user;
			state.token = data.token;
			localStorage.setItem('token', data.token);
			localStorage.setItem('user', JSON.stringify(data.user));
		}
		errorBox.textContent="";
		auth.classList.add("hidden");layout.classList.remove("hidden");userRole.textContent=`${state.user.nombre} • ${rol}`;
		state.view=rol==="repartidor"?"pedidos":"dashboard";
		await loadData();
		renderNav();renderView();showToast("Sesión iniciada");
	}catch(e){
		errorBox.textContent='Error de conexión';showToast('Error','error');
	}
}
function logout(){state.user=null;state.token=null;localStorage.removeItem('token');localStorage.removeItem('user');auth.classList.remove("hidden");layout.classList.add("hidden");document.getElementById("auth-error").textContent="";document.getElementById("usuario").value="";document.getElementById("password").value="";state.view=null;showToast("Sesión cerrada")}
function init(){today.textContent=new Date().toLocaleDateString("es-MX",{weekday:"long",day:"2-digit",month:"long",year:"numeric"});document.getElementById("entrar").onclick=login;document.getElementById("logout").onclick=logout;const storedToken=localStorage.getItem('token');const storedUser=localStorage.getItem('user');if(storedToken&&storedUser){state.token=storedToken;state.user=JSON.parse(storedUser);auth.classList.add("hidden");layout.classList.remove("hidden");userRole.textContent=`${state.user.nombre} • ${state.user.rol}`;state.view=state.user.rol==="repartidor"?"pedidos":"dashboard";loadData();renderNav();renderView()}}
init();
