const express = require("express");
const path = require("path");
const cors = require("cors");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const axios = require("axios");
const { Pool } = require("pg");
require("dotenv").config();

const app = express();
const port = process.env.PORT || 8000;

app.use(cors());
app.use(express.json());

const JWT_SECRET = process.env.JWT_SECRET || 'cambiame_por_una_secreta_en_produccion';

// Postgres (Neon) optional
const DATABASE_URL = process.env.DATABASE_URL || '';
let pgPool = null;
if (DATABASE_URL) {
  pgPool = new Pool({
    connectionString: DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });
}

// Datos en memoria (fallback) — vacíos para prod/hosting
let clientes = [];
let pedidos = [];
let ventas = [];
let inventario = [];
let gastos = [];

// Cuentas de ejemplo (passwords hashed)
const accounts = [
  {username: "admin", passwordHash: bcrypt.hashSync("agua2026", 8), rol: "admin", nombre: "Admin"},
  {username: "reparto", passwordHash: bcrypt.hashSync("ruta2026", 8), rol: "repartidor", nombre: "Reparto"}
];
let RESET_KEY = process.env.RESET_KEY || 'admin_reset_2026';

// Haversine distance (km)
function distanceKm(a,b){
  const toRad = v=>v*Math.PI/180;
  const R = 6371; // km
  const dLat = toRad(b.lat - a.lat);
  const dLon = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const sinDLat = Math.sin(dLat/2);
  const sinDLon = Math.sin(dLon/2);
  const aa = sinDLat*sinDLat + sinDLon*sinDLon * Math.cos(lat1)*Math.cos(lat2);
  const c = 2 * Math.atan2(Math.sqrt(aa), Math.sqrt(1-aa));
  return R * c;
}

// Geocode intersection of two streets in Gabriel Leyva Solano
async function geocodeIntersection(streetA, streetB){
  const query = encodeURIComponent(`${streetA} & ${streetB}, Gabriel Leyva Solano, Sinaloa, Mexico`);
  const url = `https://nominatim.openstreetmap.org/search?format=json&q=${query}&limit=1`;
  const resp = await axios.get(url, { headers: { 'User-Agent': 'SistemaPurificadora/1.0' } });
  if (resp.data && resp.data.length > 0) {
    return { lat: parseFloat(resp.data[0].lat), lng: parseFloat(resp.data[0].lon) };
  }
  return null;
}

// Base address and center (override via env BASE_LAT/BASE_LNG/BASE_LABEL)
const BASE_ADDRESS = process.env.BASE_ADDRESS || 'Ramon Corona SN-S, 81122 Gabriel Leyva Solano, Sinaloa, Mexico';
const BASE_LABEL = process.env.BASE_LABEL || 'Base';
const DELIVERY_CENTER = {
  lat: process.env.BASE_LAT ? Number(process.env.BASE_LAT) : 25.6638889,
  lng: process.env.BASE_LNG ? Number(process.env.BASE_LNG) : -108.638333
};
const DELIVERY_RADIUS_KM = Number(process.env.DELIVERY_RADIUS_KM) || 12; // km

async function initDb(){
  if(!pgPool) return;
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS clientes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre TEXT NOT NULL,
      telefono TEXT,
      direccion TEXT,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      frecuencia INTEGER,
      volumen INTEGER
    );
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS pedidos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cliente_id INTEGER REFERENCES clientes(id),
      total NUMERIC,
      estado TEXT,
      cantidad INTEGER,
      creado TIMESTAMP DEFAULT NOW(),
      notas TEXT
    );
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS ventas (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cliente_id INTEGER,
      total NUMERIC,
      metodo TEXT,
      creado TIMESTAMP DEFAULT NOW()
    );
  `);
  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS inventario (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      item TEXT,
      stock INTEGER,
      umbral INTEGER,
      precio NUMERIC
    );
  `);

  await pgPool.query(`
    CREATE TABLE IF NOT EXISTS gastos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      concepto TEXT,
      categoria TEXT,
      monto NUMERIC,
      creado TIMESTAMP DEFAULT NOW()
    );
  `);

  await pgPool.query(`ALTER TABLE inventario ADD COLUMN IF NOT EXISTS precio NUMERIC;`);
  await pgPool.query(`ALTER TABLE inventario ADD COLUMN IF NOT EXISTS umbral INTEGER;`);

  const { rows: cCount } = await pgPool.query('SELECT COUNT(*) AS count FROM clientes');
  if (Number(cCount[0].count) === 0 && clientes.length) {
    for (const c of clientes) {
      await pgPool.query(
        'INSERT INTO clientes (id, nombre, telefono, direccion, lat, lng, frecuencia, volumen) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING',
        [c.id, c.nombre, c.telefono, c.direccion, c.lat, c.lng, c.frecuencia, c.volumen]
      );
    }
  }

  const { rows: pCount } = await pgPool.query('SELECT COUNT(*) AS count FROM pedidos');
  if (Number(pCount[0].count) === 0 && pedidos.length) {
    for (const p of pedidos) {
      await pgPool.query(
        'INSERT INTO pedidos (id, cliente_id, total, estado, cantidad, creado, notas) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO NOTHING',
        [p.id, p.cliente_id, p.total, p.estado, p.cantidad, p.creado, p.notas]
      );
    }
  }

  const { rows: vCount } = await pgPool.query('SELECT COUNT(*) AS count FROM ventas');
  if (Number(vCount[0].count) === 0 && ventas.length) {
    for (const v of ventas) {
      await pgPool.query(
        'INSERT INTO ventas (id, cliente_id, total, metodo, creado) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (id) DO NOTHING',
        [v.id, v.cliente_id, v.total, v.metodo, v.creado]
      );
    }
  }

  const { rows: iCount } = await pgPool.query('SELECT COUNT(*) AS count FROM inventario');
  if (Number(iCount[0].count) === 0 && inventario.length) {
    for (const i of inventario) {
      await pgPool.query(
        'INSERT INTO inventario (id, item, stock, umbral, precio) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (id) DO NOTHING',
        [i.id, i.item, i.stock, i.umbral, i.precio]
      );
    }
  }

  const { rows: gCount } = await pgPool.query('SELECT COUNT(*) AS count FROM gastos');
  if (Number(gCount[0].count) === 0 && gastos.length) {
    for (const g of gastos) {
      await pgPool.query(
        'INSERT INTO gastos (id, concepto, categoria, monto, creado) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (id) DO NOTHING',
        [g.id, g.concepto, g.categoria, g.monto, g.creado]
      );
    }
  }

  // Ensure identity sequences are ahead of max(id) to avoid duplicate key inserts
  await pgPool.query(
    "SELECT setval(pg_get_serial_sequence('clientes','id'), GREATEST(COALESCE((SELECT MAX(id) FROM clientes), 0), 1), true)"
  );
  await pgPool.query(
    "SELECT setval(pg_get_serial_sequence('pedidos','id'), GREATEST(COALESCE((SELECT MAX(id) FROM pedidos), 0), 1), true)"
  );
  await pgPool.query(
    "SELECT setval(pg_get_serial_sequence('ventas','id'), GREATEST(COALESCE((SELECT MAX(id) FROM ventas), 0), 1), true)"
  );
  await pgPool.query(
    "SELECT setval(pg_get_serial_sequence('inventario','id'), GREATEST(COALESCE((SELECT MAX(id) FROM inventario), 0), 1), true)"
  );
  await pgPool.query(
    "SELECT setval(pg_get_serial_sequence('gastos','id'), GREATEST(COALESCE((SELECT MAX(id) FROM gastos), 0), 1), true)"
  );
}

// Helper: fetch from Postgres if configured, otherwise use in-memory
async function getClientes(zona){
  if(pgPool){
    const { rows } = await pgPool.query('SELECT * FROM clientes');
    if (!zona) return rows;
    return rows.filter(c=> c.lat && c.lng ? distanceKm(DELIVERY_CENTER,{lat:c.lat,lng:c.lng})<=DELIVERY_RADIUS_KM : true);
  }
  if (!zona) return clientes;
  return clientes.filter(c=> c.lat && c.lng ? distanceKm(DELIVERY_CENTER,{lat:c.lat,lng:c.lng})<=DELIVERY_RADIUS_KM : true);
}

async function getPedidos(zona){
  if(pgPool){
    const { rows: pedidosData } = await pgPool.query('SELECT * FROM pedidos');
    const { rows: clientesData } = await pgPool.query('SELECT * FROM clientes');
    const clientesList = clientesData || clientes;
    if (!zona) return pedidosData;
    return pedidosData.filter(p=>{
      if(!p.cliente_id) return true; // Mostrar pedidos sin cliente registrado (eventuales)
      const c = clientesList.find(x=>x.id===p.cliente_id);
      if (!c) return true; 
      if (!c.lat || !c.lng) return true;
      return distanceKm(DELIVERY_CENTER,{lat:c.lat,lng:c.lng})<=DELIVERY_RADIUS_KM;
    });
  }
  if (!zona) return pedidos;
  return pedidos.filter(p=>{
    if(!p.cliente_id) return true; // Mostrar pedidos sin cliente registrado (eventuales)
    const c = clientes.find(x=>x.id===p.cliente_id);
    if (!c) return true;
    if (!c.lat || !c.lng) return true;
    return distanceKm(DELIVERY_CENTER,{lat:c.lat,lng:c.lng})<=DELIVERY_RADIUS_KM;
  });
}

async function getVentas(){
  if(pgPool){
    const { rows } = await pgPool.query('SELECT * FROM ventas');
    return rows;
  }
  return ventas;
}

async function getInventario(){
  if(pgPool){
    const { rows } = await pgPool.query('SELECT * FROM inventario');
    return rows;
  }
  return inventario;
}

async function getGastos(){
  if(pgPool){
    const { rows } = await pgPool.query('SELECT * FROM gastos ORDER BY creado DESC');
    return rows;
  }
  return gastos;
}

function authMiddleware(req,res,next){
  const auth = req.headers.authorization;
  if(!auth) return res.status(401).json({error:'No token'});
  const parts = auth.split(' ');
  if(parts.length!==2) return res.status(401).json({error:'Invalid token'});
  const token = parts[1];
  try{
    const payload = jwt.verify(token, JWT_SECRET);
    req.user = payload;next();
  }catch(e){return res.status(401).json({error:'Invalid token'})}
}

function requireRole(roles){
  return (req,res,next)=>{
    if(!req.user || !roles.includes(req.user.rol)){
      return res.status(403).json({error:'Forbidden'});
    }
    next();
  };
}

app.get("/api/ping", (req,res)=>res.json({ok:true}));
    
// Base endpoint to share current center
app.get('/api/base', (req,res)=>{
  res.json({
    lat: DELIVERY_CENTER.lat,
    lng: DELIVERY_CENTER.lng,
    address: BASE_ADDRESS,
    label: BASE_LABEL
  });
});

app.post("/api/auth/login", async (req,res)=>{
  const {username,password,rol} = req.body || {};
  if(!username || !password) return res.status(400).json({error:"Missing credentials"});
  const acc = accounts.find(a=>a.username===username && a.rol===rol);
  if(!acc) return res.status(401).json({error:"Invalid"});
  const ok = bcrypt.compareSync(password, acc.passwordHash);
  if(!ok) return res.status(401).json({error:"Invalid"});
  const payload = {username:acc.username,rol:acc.rol,nombre:acc.nombre};
  const token = jwt.sign(payload, JWT_SECRET, {expiresIn:'8h'});
  res.json({user:payload, token});
});

app.post("/api/auth/change-password", async (req,res)=>{
  const { username, rol, currentPassword, newPassword } = req.body || {};
  if(!username || !rol || !currentPassword || !newPassword){
    return res.status(400).json({error:"Missing fields"});
  }
  const acc = accounts.find(a=>a.username===username && a.rol===rol);
  if(!acc) return res.status(404).json({error:"User not found"});
  const ok = bcrypt.compareSync(currentPassword, acc.passwordHash);
  if(!ok) return res.status(401).json({error:"Invalid password"});
  acc.passwordHash = bcrypt.hashSync(newPassword, 8);
  res.json({ok:true});
});

app.post("/api/auth/reset-password", async (req,res)=>{
  const { username, rol, resetKey, newPassword } = req.body || {};
  if(!username || !rol || !resetKey || !newPassword){
    return res.status(400).json({error:"Missing fields"});
  }
  if(resetKey !== RESET_KEY){
    return res.status(401).json({error:"Invalid reset key"});
  }
  const acc = accounts.find(a=>a.username===username && a.rol===rol);
  if(!acc) return res.status(404).json({error:"User not found"});
  acc.passwordHash = bcrypt.hashSync(newPassword, 8);
  res.json({ok:true});
});

app.post("/api/auth/admin/update-key", authMiddleware, requireRole(['admin']), async (req,res)=>{
  const { newKey } = req.body || {};
  if(!newKey) return res.status(400).json({error:"Missing new key"});
  RESET_KEY = newKey;
  res.json({ok:true});
});

app.get('/api/clientes', authMiddleware, requireRole(['admin','repartidor']), async (req,res)=>{
  const zona = req.query.zona;
  const data = await getClientes(zona);
  res.json(data);
});

app.get('/api/pedidos', authMiddleware, requireRole(['admin','repartidor']), async (req,res)=>{
  const zona = req.query.zona;
  const data = await getPedidos(zona);
  res.json(data);
});

  app.put('/api/clientes/:id', authMiddleware, requireRole(['admin']), async (req,res)=>{
    const id = Number(req.params.id);
    let { nombre, telefono, direccion, lat, lng } = req.body || {};
    
    if (!lat || !lng) {
      try {
        const dirText = (direccion || '').trim();
        let foundPoint = null;
        const entreMatch = dirText.match(/(.+?)\s+entre\s+(.+?)\s+(?:y|e)\s+(.+)/i);
        if (entreMatch) {
          const base = entreMatch[1].trim();
          const cross1 = entreMatch[2].trim();
          const cross2 = entreMatch[3].trim();
          const p1 = await geocodeIntersection(base, cross1);
          const p2 = await geocodeIntersection(base, cross2);
          if (p1 && p2) {
            foundPoint = { lat: (p1.lat + p2.lat) / 2, lng: (p1.lng + p2.lng) / 2 };
          } else if (p1) {
            foundPoint = p1;
          } else if (p2) {
            foundPoint = p2;
          }
        } else {
          foundPoint = await geocodeAddress(dirText);
        }
        if (foundPoint) {
          lat = foundPoint.lat;
          lng = foundPoint.lng;
        }
      } catch (e) {
        console.error('Error al actualizar geocodificación:', e.message);
      }
    }

    if(pgPool){
      const { rows } = await pgPool.query(
        'UPDATE clientes SET nombre = $1, telefono = $2, direccion = $3, lat = $4, lng = $5 WHERE id = $6 RETURNING *',
        [nombre, telefono, direccion, lat || null, lng || null, id]
      );
      if(rows && rows[0]) return res.json(rows[0]);
    }
    const idx = clientes.findIndex(x=>x.id===id);
    if(idx===-1) return res.status(404).json({error:"Not found"});
    clientes[idx] = { ...clientes[idx], nombre, telefono, direccion, lat, lng };
    res.json(clientes[idx]);
  });

  app.delete('/api/clientes/:id', authMiddleware, requireRole(['admin']), async (req,res)=>{
    const id = Number(req.params.id);
    if(pgPool){
      await pgPool.query('DELETE FROM clientes WHERE id = $1', [id]);
      return res.json({success:true});
    }
    const idx = clientes.findIndex(x=>x.id===id);
    if(idx>-1) clientes.splice(idx,1);
    res.json({success:true});
  });

app.post('/api/clientes', async (req,res)=>{
  let { nombre, telefono, direccion, lat, lng } = req.body;

  // Si no hay lat/lng, intentar geocodificar usando Nominatim con soportes de cruce de calles
  if (!lat || !lng) {
    try {
      const dirText = (direccion || '').trim();
      let foundPoint = null;

      // Caso: "Calle Principal entre Calle 1 y Calle 2" -> promediar los dos cruces para caer sobre la calle principal
      const entreMatch = dirText.match(/(.+?)\s+entre\s+(.+?)\s+(?:y|e)\s+(.+)/i);
      if (entreMatch) {
        const base = entreMatch[1].trim();
        const cross1 = entreMatch[2].trim();
        const cross2 = entreMatch[3].trim();
        const p1 = await geocodeIntersection(base, cross1);
        const p2 = await geocodeIntersection(base, cross2);
        if (p1 && p2) {
          foundPoint = { lat: (p1.lat + p2.lat) / 2, lng: (p1.lng + p2.lng) / 2 };
        } else if (p1) {
          foundPoint = p1;
        } else if (p2) {
          foundPoint = p2;
        }
      }

      // Caso: "Calle A y Calle B" o "Calle A & Calle B"
      if (!foundPoint) {
        const yMatch = dirText.match(/(.+?)\s+(?:y|&){1}\s+(.+)/i);
        if (yMatch) {
          const p = await geocodeIntersection(yMatch[1].trim(), yMatch[2].trim());
          if (p) foundPoint = p;
        }
      }

      // Búsqueda directa si no hubo cruces
      if (!foundPoint) {
        const query = encodeURIComponent(`${dirText}, Gabriel Leyva Solano, Sinaloa, Mexico`);
        const geoRes = await axios.get(`https://nominatim.openstreetmap.org/search?format=json&q=${query}&limit=1`, {
          headers: { 'User-Agent': 'SistemaPurificadora/1.0' }
        });
        if (geoRes.data && geoRes.data.length > 0) {
          foundPoint = { lat: parseFloat(geoRes.data[0].lat), lng: parseFloat(geoRes.data[0].lon) };
        }
      }

      if (foundPoint) {
        lat = foundPoint.lat;
        lng = foundPoint.lng;
      } else {
        // Fallback: centro con ligera variación para no encimar
        lat = DELIVERY_CENTER.lat + (Math.random() - 0.5) * 0.01;
        lng = DELIVERY_CENTER.lng + (Math.random() - 0.5) * 0.01;
      }
    } catch (e) {
      console.error("Error geocoding:", e.message);
      lat = DELIVERY_CENTER.lat;
      lng = DELIVERY_CENTER.lng;
    }
  }

  const nuevo = { nombre, telefono, direccion, lat, lng, id: Date.now() };

  if(pgPool){
    const { rows } = await pgPool.query(
      'INSERT INTO clientes (nombre, telefono, direccion, lat, lng) VALUES ($1,$2,$3,$4,$5) RETURNING *',
      [nombre, telefono, direccion, lat, lng]
    );
    if(rows && rows[0]) return res.json(rows[0]);
  }
  clientes.push(nuevo);
  res.json(nuevo);
});

app.post('/api/pedidos', async (req,res)=>{
    try {
      const { cliente_id, cantidad, notas, total } = req.body || {};
      // Payload ajustado a columnas reales: id es identity en Postgres, creado es default
      const payload = {
        cliente_id: cliente_id ? Number(cliente_id) : null,
        cantidad: Number(cantidad) || 1,
        notas: notas || '',
        total: Number(total) || 0,
        estado: 'pendiente'
      };

      if(pgPool){
        const { rows } = await pgPool.query(
          'INSERT INTO pedidos (cliente_id, cantidad, notas, total, estado) VALUES ($1,$2,$3,$4,$5) RETURNING *',
          [payload.cliente_id, payload.cantidad, payload.notas, payload.total, payload.estado]
        );
        if(rows && rows[0]) return res.json(rows[0]);
      }

      const fallback = { ...payload, id: Date.now(), creado_en: new Date().toISOString() };
      pedidos.push(fallback);
      res.json(fallback);
    } catch(err) {
      console.error('Error insertando pedido:', err);
      res.status(500).json({ error: 'Error interno guardando pedido', detalle: err.message });
    }
  });
app.post('/api/inventario', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const nuevo = { ...req.body, id: Date.now() };
  if(pgPool){
    const { rows } = await pgPool.query(
      'INSERT INTO inventario (item, stock, umbral, precio) VALUES ($1,$2,$3,$4) RETURNING *',
      [req.body.item, req.body.stock, req.body.umbral, req.body.precio]
    );
    if(rows && rows[0]) return res.json(rows[0]);
  }
  inventario.push(nuevo);
  res.json(nuevo);
});

app.put('/api/inventario/:id', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const id = Number(req.params.id);
  const { item, stock, umbral, precio } = req.body || {};
  if(pgPool){
    const { rows } = await pgPool.query(
      'UPDATE inventario SET item = $1, stock = $2, umbral = $3, precio = $4 WHERE id = $5 RETURNING *',
      [item, stock, umbral, precio, id]
    );
    if(rows && rows[0]) return res.json(rows[0]);
  }
  const idx = inventario.findIndex(x=>x.id===id);
  if(idx === -1) return res.status(404).json({error:'Not found'});
  inventario[idx] = { ...inventario[idx], item, stock, umbral, precio };
  res.json(inventario[idx]);
});

app.post('/api/pedidos/:id/state', authMiddleware, requireRole(['admin','repartidor']), async (req,res)=>{
  const id = Number(req.params.id);
  const {estado} = req.body || {};
  // update in Postgres or memory
  if(pgPool){
    const { rows } = await pgPool.query(
      'UPDATE pedidos SET estado = $1 WHERE id = $2 RETURNING *',
      [estado, id]
    );
    if(rows && rows[0]) return res.json(rows[0]);
  }
  const p = pedidos.find(x=>x.id===id);
  if(!p) return res.status(404).json({error:"Not found"});
  p.estado = estado || p.estado;
  res.json(p);
});

app.delete('/api/pedidos/:id', authMiddleware, requireRole(['admin', 'repartidor']), async (req,res)=>{
  const id = Number(req.params.id);
  if(pgPool){
    await pgPool.query('DELETE FROM pedidos WHERE id = $1', [id]);
    return res.json({success:true});
  }
  const idx = pedidos.findIndex(x=>x.id===id);
  if(idx > -1) pedidos.splice(idx, 1);
  res.json({success:true});
});

app.get('/api/ventas', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const data = await getVentas();
  res.json(data);
});

app.get('/api/inventario', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const data = await getInventario();
  res.json(data);
});

app.get('/api/gastos', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const data = await getGastos();
  res.json(data);
});

app.post('/api/gastos', authMiddleware, requireRole(['admin']), async (req,res)=>{
  const { concepto, categoria, monto } = req.body || {};
  const payload = { concepto, categoria, monto: Number(monto) };
  if(pgPool){
    const { rows } = await pgPool.query(
      'INSERT INTO gastos (concepto, categoria, monto) VALUES ($1,$2,$3) RETURNING *',
      [payload.concepto, payload.categoria, payload.monto]
    );
    if(rows && rows[0]) return res.json(rows[0]);
  }
  const fallback = { ...payload, id: Date.now(), creado: new Date().toISOString() };
  gastos.push(fallback);
  res.json(fallback);
});

// Route optimization: use OpenRouteService if API key provided, otherwise greedy fallback
app.post('/api/rutas/optimize', authMiddleware, requireRole(['admin','repartidor']), async (req,res)=>{
  const items = req.body.items || [];
  // items: array of {id, lat, lng}
  // helper: greedy order (used both for fallback and to give directions a reasonable path)
  const orderGreedy = (list)=>{
    const start = {lat:DELIVERY_CENTER.lat,lng:DELIVERY_CENTER.lng};
    const remaining = list.slice();
    const ordered = [];
    let current = start;
    while(remaining.length){
      remaining.sort((a,b)=>{
        const da = distanceKm(current,{lat:a.lat,lng:a.lng});
        const db = distanceKm(current,{lat:b.lat,lng:b.lng});
        return da-db;
      });
      const next = remaining.shift();
      ordered.push(next);
      current = {lat:next.lat,lng:next.lng};
    }
    return ordered;
  };

  const orderedItems = orderGreedy(items);

  if (orderedItems.length === 0) {
    return res.json({route: [], geometry: []});
  }

  if(process.env.ORS_API_KEY && orderedItems.length){
    try{
      // Build coordinates starting from the delivery center so the geometry begins at base
      const coords = [ [DELIVERY_CENTER.lng, DELIVERY_CENTER.lat], ...orderedItems.map(i=>[i.lng,i.lat]) ];
      const body = {coordinates: coords};
      const orsUrl = 'https://api.openrouteservice.org/v2/directions/driving-car/geojson';
      const resp = await axios.post(orsUrl, body, {
        headers:{Authorization: process.env.ORS_API_KEY,'Content-Type':'application/json'}
      });
      const geometry = resp.data?.features?.[0]?.geometry?.coordinates || [];
      return res.json({route: orderedItems, geometry});
    }catch(e){
      const status = e.response?.status;
      if (status === 404) {
        try {
          const fallbackUrl = 'https://api.openrouteservice.org/v2/directions/driving-car';
          const resp = await axios.post(fallbackUrl, body, {
            headers:{Authorization: process.env.ORS_API_KEY,'Content-Type':'application/json'},
            params:{format:'geojson'}
          });
          const geometry = resp.data?.features?.[0]?.geometry?.coordinates || [];
          return res.json({route: orderedItems, geometry});
        } catch (inner) {
          console.error('ORS fallback error:', inner.response?.status || inner.message);
        }
      } else {
        console.error('ORS directions error:', status || e.message);
      }
      // fall through to greedy polyline without streets
    }
  }

  // OSRM fallback for street-following geometry (no API key)
  try{
    const coords = [ [DELIVERY_CENTER.lng, DELIVERY_CENTER.lat], ...orderedItems.map(i=>[i.lng,i.lat]) ];
    const coordString = coords.map(c => `${c[0]},${c[1]}`).join(';');
    const osrmUrl = `https://router.project-osrm.org/route/v1/driving/${coordString}`;
    const resp = await axios.get(osrmUrl, { params: { overview: 'full', geometries: 'geojson' } });
    const geometry = resp.data?.routes?.[0]?.geometry?.coordinates || [];
    if (geometry.length) {
      return res.json({route: orderedItems, geometry});
    }
  }catch(e){
    console.error('OSRM directions error:', e.response?.status || e.message);
  }

  // fallback: greedy nearest-neighbor and straight segments
  const route = orderedItems;
  const geometry = [ [DELIVERY_CENTER.lng, DELIVERY_CENTER.lat], ...route.map(i=>[i.lng,i.lat]) ];
  res.json({route, geometry});
});

// Servir archivos estáticos (HTML/CSS/JS)
app.use(express.static(path.join(__dirname, 'frontend/dist')));

app.get('*', (req,res)=>{
  res.sendFile(path.join(__dirname, 'frontend/dist', 'index.html'));
});

async function startServer(){
  try{
    await initDb();
    app.listen(port, ()=>{
      console.log(`Server listening on http://localhost:${port}`);
    });
  }catch(e){
    console.error('Failed to start server:', e.message);
    process.exit(1);
  }
}

startServer();
